version: "2"
services:
    mysql:
        image: mysql:5.7
        container_name: mysql_tm
        environment:
            MYSQL_ROOT_PASSWORD: toor
        volumes:
            - db:/var/lib/mysql
            - ./mysql/my.cnf:/etc/mysql/conf.d/my.cnf
        ports:
            - "3306:3306"

    php:
        build: ./docker/php
        container_name: php_tm
        ports:
            - "8000:80"
        volumes:
            - ./:/var/www/
            # - $HOME/.composer/:$HOME/.composer/
        links:
            - mysql:db
        depends_on:
            - mysql

    nginx:
        image: jguyomard/laravel-nginx:1.13
        container_name: nginx_tm
        volumes_from:
            - php
        ports:
            - 80:80

    admin:
        image: "phpmyadmin/phpmyadmin"
        container_name: admin_tm
        ports:
            - "8060:80"
        links:
            - mysql:db
        depends_on:
            - mysql
    #    ports:
    #        - "3306:3306"

    redis:
        image: redis:4.0-alpine
        command: redis-server --appendonly yes
#    ports:
#        - "6379:6379"

#  elastic:
#    image: elasticsearch:5.5-alpine
#    ports:
#        - "9200:9200"

volumes:
    db:
